language: node_js
compiler: clang-3.6
node_js:
  - "5.0"
  - "4.1"
  - "4.0"
cache:
  directories:
    - "node_modules"
    - "bower_components"
addons:
  firefox: "latest"
env:
  global:
    - secure: "Arph6QlNiZQM9QVngvypyPZDVMUW0EdUdJ8lEHWl31QajF7lq5Qd6y53ONsI0onYvE5luTfDYDn39eiYHhiQiCC7oTFE3yMSyCEizE0mkiwV9PUupRDpKSEj+C9vlVwQsen0gSEOnn8C07ZUrZaZDiOyurd5UaSrk9eKNobhawBYb49b1OzedX65eWHTC4J5YCKAXM28h+pAU0bqF2loE2bbTGgGVGyRz8CH1WUdo3DM5AMB3uqY3EbmGJXj3J9M0TsOLsdmvJs4V5TBnxVUEM/oKzSlh9ywhjDQStvubMK56JoItpnjf50Ksjb4Y2FibsxBFAVQhQrEaVQS9oxEPm3NuCEj6JzIwx97M8/PJNC9tc95blhyRRIsqVcEOaLn0qwnArXGGvR7hBtbTLU9J0b05RDKwJljY/s2BvOFpBjgOOP/MdMMBPM0nS3cTiLZgWGfvVYinaXLmuXEYEbsJP8bVHnozC76Sb+mEeowX1qrbzOn3BFntAVbggAOGDmadCElIrWdyLuOvWYPAvTXTqbZqeQ1ziMFa2PmMy2mbPcKgbtHX6uRlv+l2Zd3lMaIt7y+DYh75R296816ut4HfoN3hHFgw2H9u5iYstY48+Toty9QPZfEJrZScJlIlz59iBlmZL8bJTsTtce62p9Y0iWpNTCS5YskGsDPex5zOUE="
  matrix:
    - "mode=CI DISPLAY=:99.0 CXX=clang-3.6"
before_script:
  - "sh -e /etc/init.d/xvfb start"
script:
  - "gulp"
  - "gulp e2e.firefox"
after_success:
  - "sh -e ./deploy"
