language: node_js
node_js:
  - "5.0"
  - "4.1"
  - "4.0"
cache:
  directories:
    - "node_modules"
    - "bower_components"
addons:
  firefox: "latest"
env:
  matrix:
    - "mode=CI DISPLAY=:99.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
script:
  - "gulp"
  - "gulp e2e.firefox"
after_success:
  - "echo \"tag: ${TRAVIS_TAG}\""
