#!/bin/sh -e

if [ "${TRAVIS_BRANCH}" != "master" ]; then
  echo "This deployment script is written for master branch only. Not supported: ${TRAVIS_BRANCH}"
  exit 0
fi

repo="~/bower-angular-tag-editor"

push_tag() {
  if [ -n "${TRAVIS_TAG}" ]; then
    echo "Pushing tag..."
    cd ${repo}
    git tag -a "${TRAVIS_TAG}" -m "Version: ${TRAVIS_TAG}"
    git push -q origin --tag ${TRAVIS_TAG}
    cd -
    echo "Done."
  fi
}

clone_or_pull() {
  echo "Cloning/Pulling repo"
  if ! [ -d ${repo} ]; then
    git clone -q https://hiroaki-yamamoto:${token}@github.com/Forumouth/bower-angular-tageditor.git ${repo}
    cd ${repo}
  else
    cd ${repo}
    git pull -q origin
  fi
  cd -
  echo "Done."
}

copy_files() {
  echo "Copying compiled files and some extras..."
  rsync -aCP --delete --exclude-from=./rsync.cfg --include-from=./rsync.cfg . ${repo}
  echo "Done."
}


deploy () {
  echo "Deploying to the repo..."
  cd ${repo}
  git add .
  git config user.name "Hiroaki Yamamoto (From Travis CI)"
  git config user.email "hiroaki-yamamoto@users.noreply.github.com"
  git commit -m "[TRAVIS DEPLOY BOT] COMMIT: ${TRAVIS_COMMIT}"
  git push -q origin master || {
    git reset --hard HEAD
    echo "Failed. the repo already up-to-date.";
  }
  cd -
  echo "Done."
}

clone_or_pull
copy_files
deploy
push_tag
